# dacon_titanic
## pycaret - 정확도 : 0.74734 / 첫 시도
## tpot - 정확도 : 0.8340 / 첫 시도
## autosklearn - m1 / 에러발생 : ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': "<class 'pynisher.limit_function_call.AnythingException'>", 'subprocess_stdout': '', 'subprocess_stderr': 'Process pynisher function call:\nTraceback (most recent call last):\n  File "/opt/anaconda3/envs/autosk/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap\n    self.run()\n  File "/opt/anaconda3/envs/autosk/lib/python3.7/multiprocessing/process.py", line 99, in run\n    self._target(*self._args, **self._kwargs)\n  File "/opt/anaconda3/envs/autosk/lib/python3.7/site-packages/pynisher/limit_function_call.py", line 108, in subprocess_func\n    resource.setrlimit(resource.RLIMIT_AS, (mem_in_b, mem_in_b))\nValueError: current limit exceeds maximum limit\n', 'exitcode': 1, 'configuration_origin': 'DUMMY'}.
